# This signifies that this is a .yml file
---
    name: Checks

    # Trigger
    on:
      push:

    jobs:
      test-lint:
        name: Build and Run
        runs-on: ubuntu-20.04
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build
            run: docker compose build
          - name: Run
            run: docker compose up -d

